lenguage: node_js
cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn build

notifications:
  slack: mau02ro:ySKpw6qB6JlrUgYEKWjvHaKG 
  email:
    recipients:
      - maurojhg2019developer@gmail.com
    on_seccess: always
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy de proyecto"
  on:
    branch: master

